
server:
  port: 8080
  servlet:
    context-path: /backend
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/backend}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

cloudinary:
  cloud-name: dx3mcnnfa
  api-key: 763191867466888
  api-secret: AvAmuie9XZJ96n00-dkGdPGH6ho

jwt:
  signerKey: "5WoxGcesYyP6K3ewuX0ub/rNJmRaIXU4cxzugMlnzFoco0QVHaPv2nMxWY8Bhi03"
  valid-duration: 3600 #in second
  refreshable-duration: 360000 # in seconds

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE
